Programs-Directory: C:\Users\Xeology\Documents\NetBeansProjects\Fault\game\programs
Rounds: 20
Cells: 500
Memory-Blocks: 50
Use-Program-List: false
Program-List:
- virus
- virus3
Max-Cycles: 200
Debug-Mode: false
Use-GUI: true
